add lecture02.md
NatsumiAkiyama/RaiseTech pull request #1
Opened 2023-06-04 01:28 UTC by NatsumiAkiyama

第2回の課題を提出いたします。ご確認お願いいたします。

2023-06-08 12:32 UTC, MasatoshiMizumoto requested changes
内容はOKですが、書き方を1点コメントしましたのでご対応ください！

2023-06-08 12:32 UTC, MasatoshiMizumoto commented on lecture02.md
> +<br>　　③ローカルのデータを反映する「push」
この表記だと番号付きリストのほうが良いかなと思います！
```suggestion
1. リモートのデータを取得する「git clone」
2. ファイル変更を履歴に反映する「commit」または「add」
3. ローカルのデータを反映する「push」
```

2023-06-13 21:46 UTC, NatsumiAkiyama reviewed
ご指摘いただいた点を修正しました！ご確認いただけますと幸いです。

2023-06-14 00:52 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-06-14 21:20 UTC, merged